# Generated by Django 6.0.3 on 2026-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Restaurant Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='avg_prepare_time',
            field=models.PositiveIntegerField(default=30, verbose_name='Average Prepare Time (minutes)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_covers/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Restaurant Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Minimum Order ($)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Restaurant Phone'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time_slot_interval',
            field=models.PositiveIntegerField(default=15, verbose_name='Time Slot Interval (minutes)'),
        ),
    ]
