# Generated by Django 4.2.11 on 2026-03-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurant_address_restaurant_avg_prepare_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('restaurant', 'order_number')},
        ),
    ]
